name: Common Steps

description: Common steps for workflows

inputs:
  gradle-encryption-key:
    description: 'Encryption key for Gradle cache'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        distribution: zulu
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
      with:
        add-job-summary-as-pr-comment: on-failure
        artifact-retention-days: 7
        build-scan-publish: true
        build-scan-terms-of-use-url: https://gradle.com/help/legal-terms-of-use
        build-scan-terms-of-use-agree: yes
        cache-encryption-key: ${{ inputs.gradle-encryption-key }}
        dependency-graph: generate-and-submit
