name: Generate build flavored local.properties
description: 'Generates a local-<flavor>.properties file dynamically for CI builds'

inputs:
  build-flavor:
    description: 'Target build flavor (e.g., dev, internal, release)'
    required: true
    default: 'dev'

  keystore-path:
    description: 'Relative path where the keystore file will be stored during build'
    required: true

  keystore-password:
    description: 'Password to unlock the keystore file'
    required: true

  key-alias:
    description: 'Alias name for the key entry inside the keystore'
    required: true

  key-password:
    description: 'Password for the key alias entry'
    required: true

runs:
  using: "composite"
  steps:
    - name: Define environment variables
      shell: bash
      run: |
        FLAVOR="${{ inputs.build-flavor }}"
        echo "FLAVOR=${FLAVOR}" >> $GITHUB_ENV
        echo "FILE_NAME=local-${FLAVOR}.properties" >> $GITHUB_ENV

    - name: Ensure $FILE_NAME exists
      shell: bash
      run: |
        echo "🔧 Checking if ${FILE_NAME} exists..."
        if [ ! -f "${FILE_NAME}" ]; then
          echo "Creating ${FILE_NAME}..."
          touch "${FILE_NAME}"
        else
          echo "${FILE_NAME} already exists. Skipping creation."
        fi

    - name: Generate local properties file for the specified flavor
      shell: bash
      run: |
        echo "keystore.path=${{ inputs.keystore-path }}" >> ${FILE_NAME}
        echo "keystore.password=${{ inputs.keystore-password }}" >> ${FILE_NAME}
        echo "key.alias=${{ inputs.key-alias }}" >> ${FILE_NAME}
        echo "key.password=${{ inputs.key-password }}" >> ${FILE_NAME}
