package com.parksupark.soomjae.core.presentation.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.SelectableChipColors
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class SoomjaeColors(
    val primary: Color,
    val secondary1: Color,
    val secondary2: Color,
    val secondary3: Color,
    val background1: Color,
    val background2: Color,
    val background3: Color,
    val background4: Color,
    val text1: Color,
    val text2: Color,
    val text3: Color,
    val text4: Color,
    val text1W: Color,
    val text2W: Color,
    val text3W: Color,
    val divider1: Color,
    val divider2: Color,
    val icon: Color,
    val iconColored: Color,
    val iconDisabled: Color,
    val iconW: Color,
    val success: Color,
    val warning: Color,
    val error: Color,
    val info: Color,
    val cta: Color,
    val ctaHover: Color,
    val ctaDisabled: Color,
    val ctaSecondary: Color,
    val ctaSecondaryHover: Color,
    val ctaSecondaryText: Color,
    val ctaTertiary: Color,
    val ctaTertiaryHover: Color,
    val ctaTertiaryText: Color,
    val ctaTertiaryStroke: Color,
) {
    internal var defaultFilterChipColorsCached: SelectableChipColors? = null
}

internal val LightColorPalette = SoomjaeColors(
    primary = Blue500,
    secondary1 = Orange700,
    secondary2 = Blue200,
    secondary3 = Navy900,
    background1 = Neutral0,
    background2 = Neutral100,
    background3 = Neutral200,
    background4 = Neutral300,
    text1 = Neutral1000,
    text2 = Neutral800,
    text3 = Neutral600,
    text4 = Neutral300,
    text1W = Neutral0,
    text2W = Neutral200,
    text3W = Neutral300,
    divider1 = Neutral200,
    divider2 = Neutral300,
    icon = Neutral800,
    iconColored = Blue500,
    iconDisabled = Neutral400,
    iconW = Neutral0,
    success = Green600,
    warning = Orange600,
    error = Red600,
    info = Blue200,
    cta = Blue500,
    ctaHover = Blue700,
    ctaDisabled = Neutral200,
    ctaSecondary = Blue50,
    ctaSecondaryHover = Blue100,
    ctaSecondaryText = Blue600,
    ctaTertiary = Neutral0,
    ctaTertiaryHover = Neutral200,
    ctaTertiaryText = Neutral800,
    ctaTertiaryStroke = Neutral200,
)

internal val DarkColorPalette = SoomjaeColors(
    primary = Blue300,
    secondary1 = Orange600,
    secondary2 = Blue100,
    secondary3 = Navy600,
    background1 = Neutral1100,
    background2 = Neutral1000,
    background3 = Neutral900,
    background4 = Neutral700,
    text1 = Neutral0,
    text2 = Neutral200,
    text3 = Neutral300,
    text4 = Neutral400,
    text1W = Neutral0,
    text2W = Neutral200,
    text3W = Neutral300,
    divider1 = Neutral800,
    divider2 = Neutral700,
    icon = Neutral100,
    iconColored = Blue300,
    iconDisabled = Neutral700,
    iconW = Neutral0,
    success = Green600,
    warning = Orange600,
    error = Red600,
    info = Blue200,
    cta = Blue300,
    ctaHover = Blue400,
    ctaDisabled = Neutral800,
    ctaSecondary = Blue50,
    ctaSecondaryHover = Blue100,
    ctaSecondaryText = Blue600,
    ctaTertiary = Neutral1100,
    ctaTertiaryHover = Neutral900,
    ctaTertiaryText = Neutral200,
    ctaTertiaryStroke = Neutral800,
)

internal fun debugColorScheme(
    darkTheme: Boolean,
    debugColor: Color = Color.Magenta,
) = ColorScheme(
    primary = debugColor,
    onPrimary = debugColor,
    primaryContainer = debugColor,
    onPrimaryContainer = debugColor,
    inversePrimary = debugColor,
    secondary = debugColor,
    onSecondary = debugColor,
    secondaryContainer = debugColor,
    onSecondaryContainer = debugColor,
    tertiary = debugColor,
    onTertiary = debugColor,
    tertiaryContainer = debugColor,
    onTertiaryContainer = debugColor,
    background = debugColor,
    onBackground = debugColor,
    surface = debugColor,
    onSurface = debugColor,
    surfaceVariant = debugColor,
    onSurfaceVariant = debugColor,
    surfaceTint = debugColor,
    inverseSurface = debugColor,
    inverseOnSurface = debugColor,
    error = debugColor,
    onError = debugColor,
    errorContainer = debugColor,
    onErrorContainer = debugColor,
    outline = debugColor,
    outlineVariant = debugColor,
    scrim = debugColor,
    surfaceBright = debugColor,
    surfaceDim = debugColor,
    surfaceContainer = debugColor,
    surfaceContainerHigh = debugColor,
    surfaceContainerHighest = debugColor,
    surfaceContainerLow = debugColor,
    surfaceContainerLowest = debugColor,
)
